apiVersion: v1
kind: Service
metadata:
  name: {{include "minecraft-server.fullname" .}}
  labels: {{- include "minecraft-server.labels" . | nindent 4}}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: mcraft
      protocol: TCP
      name: mcraft
  selector: {{- include "minecraft-server.selectorLabels" . | nindent 4}}
